service: committrs

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-east-1
  memorySize: 1024

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.committrs.io
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: '*.committrs.io'

functions:
  app:
    handler: dist/app.app
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

